// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_usuario_ConAuth_cesta_cesta from "./routes/(usuario)/(ConAuth)/(cesta)/cesta.tsx";
import * as $_usuario_ConAuth_middleware from "./routes/(usuario)/(ConAuth)/_middleware.ts";
import * as $_usuario_ConAuth_modificar_datos from "./routes/(usuario)/(ConAuth)/modificar-datos.tsx";
import * as $_usuario_ConAuth_pedidos from "./routes/(usuario)/(ConAuth)/pedidos.tsx";
import * as $_usuario_producto_id_ from "./routes/(usuario)/producto/[id].tsx";
import * as $_usuario_productos from "./routes/(usuario)/productos.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_Datos_actualizarDatos from "./routes/api/Datos/actualizarDatos.ts";
import * as $api_Datos_obtenerDatos from "./routes/api/Datos/obtenerDatos.ts";
import * as $api_auth_RecuperarContraseña from "./routes/api/auth/RecuperarContraseña.ts";
import * as $api_auth_RestablecerContraseña from "./routes/api/auth/RestablecerContraseña.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_cesta_id_ from "./routes/api/cesta/[id].ts";
import * as $api_cesta_actualizarCantidad from "./routes/api/cesta/actualizarCantidad.ts";
import * as $api_cesta_añadir from "./routes/api/cesta/añadir.ts";
import * as $api_cesta_checkBioequivalente from "./routes/api/cesta/checkBioequivalente.ts";
import * as $api_cesta_realizarPedido from "./routes/api/cesta/realizarPedido.ts";
import * as $api_farmacia_solicitudesFarmacia_SEE from "./routes/api/farmacia/solicitudesFarmacia/SEE.ts";
import * as $api_farmacia_solicitudesFarmacia_aceptar from "./routes/api/farmacia/solicitudesFarmacia/aceptar.ts";
import * as $api_farmacia_solicitudesFarmacia_finalizar from "./routes/api/farmacia/solicitudesFarmacia/finalizar.ts";
import * as $api_farmacia_solicitudesFarmacia_pedidos from "./routes/api/farmacia/solicitudesFarmacia/pedidos.ts";
import * as $api_farmacia_solicitudesFarmacia_rechazar from "./routes/api/farmacia/solicitudesFarmacia/rechazar.ts";
import * as $api_mapa_farmacias from "./routes/api/mapa/farmacias.ts";
import * as $api_mapa_ruta from "./routes/api/mapa/ruta.ts";
import * as $api_pedidos_cancelar from "./routes/api/pedidos/cancelar.ts";
import * as $api_pedidos_obtenerPedidos from "./routes/api/pedidos/obtenerPedidos.ts";
import * as $api_pedidos_repetir from "./routes/api/pedidos/repetir.ts";
import * as $api_producto_id_ from "./routes/api/producto/[id].ts";
import * as $api_producto_añadir from "./routes/api/producto/añadir.ts";
import * as $api_producto_productosCesta from "./routes/api/producto/productosCesta.ts";
import * as $api_productos from "./routes/api/productos.ts";
import * as $auth_middleware from "./routes/auth/_middleware.ts";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_recuperar_contraseña from "./routes/auth/recuperar-contraseña.tsx";
import * as $auth_register from "./routes/auth/register.tsx";
import * as $auth_restablecer_contraseña from "./routes/auth/restablecer-contraseña.tsx";
import * as $farmacia_aceptados from "./routes/farmacia/aceptados.tsx";
import * as $farmacia_finalizados from "./routes/farmacia/finalizados.tsx";
import * as $farmacia_solicitudes from "./routes/farmacia/solicitudes.tsx";
import * as $index from "./routes/index.tsx";
import * as $preguntas_frecuentes from "./routes/preguntas-frecuentes.tsx";
import * as $protección_de_datos from "./routes/protección-de-datos.tsx";
import * as $BotonSolicitarProducto from "./islands/BotonSolicitarProducto.tsx";
import * as $Buscador from "./islands/Buscador.tsx";
import * as $CestaComponent from "./islands/CestaComponent.tsx";
import * as $GestionPedidosFarmacias from "./islands/GestionPedidosFarmacias.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MapaFarmacias from "./islands/MapaFarmacias.tsx";
import * as $ModificarDatos from "./islands/ModificarDatos.tsx";
import * as $Pedidos from "./islands/Pedidos.tsx";
import * as $RecuperarContraseña from "./islands/RecuperarContraseña.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $RestablecerContraseña from "./islands/RestablecerContraseña.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(usuario)/(ConAuth)/(cesta)/cesta.tsx": $_usuario_ConAuth_cesta_cesta,
    "./routes/(usuario)/(ConAuth)/_middleware.ts": $_usuario_ConAuth_middleware,
    "./routes/(usuario)/(ConAuth)/modificar-datos.tsx": $_usuario_ConAuth_modificar_datos,
    "./routes/(usuario)/(ConAuth)/pedidos.tsx": $_usuario_ConAuth_pedidos,
    "./routes/(usuario)/producto/[id].tsx": $_usuario_producto_id_,
    "./routes/(usuario)/productos.tsx": $_usuario_productos,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/Datos/actualizarDatos.ts": $api_Datos_actualizarDatos,
    "./routes/api/Datos/obtenerDatos.ts": $api_Datos_obtenerDatos,
    "./routes/api/auth/RecuperarContraseña.ts": $api_auth_RecuperarContraseña,
    "./routes/api/auth/RestablecerContraseña.ts": $api_auth_RestablecerContraseña,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/cesta/[id].ts": $api_cesta_id_,
    "./routes/api/cesta/actualizarCantidad.ts": $api_cesta_actualizarCantidad,
    "./routes/api/cesta/añadir.ts": $api_cesta_añadir,
    "./routes/api/cesta/checkBioequivalente.ts": $api_cesta_checkBioequivalente,
    "./routes/api/cesta/realizarPedido.ts": $api_cesta_realizarPedido,
    "./routes/api/farmacia/solicitudesFarmacia/SEE.ts": $api_farmacia_solicitudesFarmacia_SEE,
    "./routes/api/farmacia/solicitudesFarmacia/aceptar.ts":
      $api_farmacia_solicitudesFarmacia_aceptar,
    "./routes/api/farmacia/solicitudesFarmacia/finalizar.ts":
      $api_farmacia_solicitudesFarmacia_finalizar,
    "./routes/api/farmacia/solicitudesFarmacia/pedidos.ts":
      $api_farmacia_solicitudesFarmacia_pedidos,
    "./routes/api/farmacia/solicitudesFarmacia/rechazar.ts":
      $api_farmacia_solicitudesFarmacia_rechazar,
    "./routes/api/mapa/farmacias.ts": $api_mapa_farmacias,
    "./routes/api/mapa/ruta.ts": $api_mapa_ruta,
    "./routes/api/pedidos/cancelar.ts": $api_pedidos_cancelar,
    "./routes/api/pedidos/obtenerPedidos.ts": $api_pedidos_obtenerPedidos,
    "./routes/api/pedidos/repetir.ts": $api_pedidos_repetir,
    "./routes/api/producto/[id].ts": $api_producto_id_,
    "./routes/api/producto/añadir.ts": $api_producto_añadir,
    "./routes/api/producto/productosCesta.ts": $api_producto_productosCesta,
    "./routes/api/productos.ts": $api_productos,
    "./routes/auth/_middleware.ts": $auth_middleware,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/recuperar-contraseña.tsx": $auth_recuperar_contraseña,
    "./routes/auth/register.tsx": $auth_register,
    "./routes/auth/restablecer-contraseña.tsx": $auth_restablecer_contraseña,
    "./routes/farmacia/aceptados.tsx": $farmacia_aceptados,
    "./routes/farmacia/finalizados.tsx": $farmacia_finalizados,
    "./routes/farmacia/solicitudes.tsx": $farmacia_solicitudes,
    "./routes/index.tsx": $index,
    "./routes/preguntas-frecuentes.tsx": $preguntas_frecuentes,
    "./routes/protección-de-datos.tsx": $protección_de_datos,
  },
  islands: {
    "./islands/BotonSolicitarProducto.tsx": $BotonSolicitarProducto,
    "./islands/Buscador.tsx": $Buscador,
    "./islands/CestaComponent.tsx": $CestaComponent,
    "./islands/GestionPedidosFarmacias.tsx": $GestionPedidosFarmacias,
    "./islands/Header.tsx": $Header,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MapaFarmacias.tsx": $MapaFarmacias,
    "./islands/ModificarDatos.tsx": $ModificarDatos,
    "./islands/Pedidos.tsx": $Pedidos,
    "./islands/RecuperarContraseña.tsx": $RecuperarContraseña,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/RestablecerContraseña.tsx": $RestablecerContraseña,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
